#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DEFAULTS_PATH = path.resolve(HERE, '../src/calibration/tripo-defaults.json');
const defaults = JSON.parse(fs.readFileSync(DEFAULTS_PATH, 'utf8'));

const args = process.argv.slice(2);
if (!args.length || args.includes('--help') || args.includes('-h')) {
  console.log(`Usage:\n  node tools/facialize-model.mjs <model.glb> [--out profile.json] [--name CharacterName]\n\nBuild-time only. Generates a Head-locked face overlay profile; runtime performs no raycasts.`);
  process.exit(args.length ? 0 : 1);
}
const modelPath = path.resolve(args[0]);
const getArg = (name, fallback=null) => { const i=args.indexOf(name); return i>=0 && args[i+1] ? args[i+1] : fallback; };
const charName = getArg('--name', path.basename(modelPath, path.extname(modelPath)));
const outPath = path.resolve(getArg('--out', `${modelPath.replace(/\.glb$/i,'')}.face-profile.json`));

const COMPONENT = {5120:{size:1,get:'getInt8'},5121:{size:1,get:'getUint8'},5122:{size:2,get:'getInt16'},5123:{size:2,get:'getUint16'},5125:{size:4,get:'getUint32'},5126:{size:4,get:'getFloat32'}};
const TYPE_COUNT={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),muls=(a,s)=>a.map(v=>v*s),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len=a=>Math.sqrt(dot(a,a)),norm=a=>{const l=len(a)||1;return a.map(v=>v/l)};

function parseGLB(file){const buf=fs.readFileSync(file);if(buf.readUInt32LE(0)!==0x46546c67)throw new Error('Only binary .glb is supported by the automatic build-time calibrator.');const version=buf.readUInt32LE(4);if(version!==2)throw new Error(`Unsupported GLB version ${version}`);let off=12,json=null,bin=null;while(off<buf.length){const l=buf.readUInt32LE(off),t=buf.readUInt32LE(off+4),d=buf.subarray(off+8,off+8+l);off+=8+l;if(t===0x4E4F534A)json=JSON.parse(d.toString('utf8').replace(/\0+$/,'').trim());if(t===0x004E4942)bin=d;}if(!json||!bin)throw new Error('GLB JSON/BIN chunk missing.');return{json,bin};}
function readAccessor(gltf,bin,index){const a=gltf.accessors[index],bv=gltf.bufferViews[a.bufferView],comp=COMPONENT[a.componentType];if(!comp)throw new Error(`Unsupported component type ${a.componentType}`);const n=TYPE_COUNT[a.type],stride=bv.byteStride??comp.size*n,start=(bv.byteOffset??0)+(a.byteOffset??0),view=new DataView(bin.buffer,bin.byteOffset,bin.byteLength),rows=[];for(let i=0;i<a.count;i++){const row=[],base=start+i*stride;for(let k=0;k<n;k++){let v=view[comp.get](base+k*comp.size,true);if(a.normalized&&a.componentType!==5126){if(a.componentType===5121)v/=255;else if(a.componentType===5123)v/=65535;else if(a.componentType===5120)v=Math.max(v/127,-1);else if(a.componentType===5122)v=Math.max(v/32767,-1);}row.push(v);}rows.push(row);}return rows;}
function ident(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];}
function mmul(a,b){const r=Array(16).fill(0);for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++)r[i*4+j]+=a[i*4+k]*b[k*4+j];return r;}
function translate(t){const m=ident();m[3]=t[0];m[7]=t[1];m[11]=t[2];return m;}
function scale(s){return[s[0],0,0,0,0,s[1],0,0,0,0,s[2],0,0,0,0,1];}
function quatMatrix(q){const[x,y,z,w]=q;return[1-2*y*y-2*z*z,2*x*y-2*z*w,2*x*z+2*y*w,0,2*x*y+2*z*w,1-2*x*x-2*z*z,2*y*z-2*x*w,0,2*x*z-2*y*w,2*y*z+2*x*w,1-2*x*x-2*y*y,0,0,0,0,1];}
function nodeLocal(n){if(n.matrix){const x=n.matrix;return[x[0],x[4],x[8],x[12],x[1],x[5],x[9],x[13],x[2],x[6],x[10],x[14],x[3],x[7],x[11],x[15]];}return mmul(mmul(translate(n.translation??[0,0,0]),quatMatrix(n.rotation??[0,0,0,1])),scale(n.scale??[1,1,1]));}
function transformPoint(m,p){return[m[0]*p[0]+m[1]*p[1]+m[2]*p[2]+m[3],m[4]*p[0]+m[5]*p[1]+m[6]*p[2]+m[7],m[8]*p[0]+m[9]*p[1]+m[10]*p[2]+m[11]];}
function inv4(m){const a=[0,1,2,3].map(i=>[...m.slice(i*4,i*4+4),...[0,1,2,3].map(j=>i===j?1:0)]);for(let c=0;c<4;c++){let p=c;for(let r=c+1;r<4;r++)if(Math.abs(a[r][c])>Math.abs(a[p][c]))p=r;if(Math.abs(a[p][c])<1e-12)throw new Error('Singular node matrix');[a[c],a[p]]=[a[p],a[c]];const d=a[c][c];a[c]=a[c].map(v=>v/d);for(let r=0;r<4;r++)if(r!==c){const f=a[r][c];a[r]=a[r].map((v,j)=>v-f*a[c][j]);}}return a.flatMap(r=>r.slice(4));}
function transformNormalBetween(m,n){const a=[[m[0],m[1],m[2]],[m[4],m[5],m[6]],[m[8],m[9],m[10]]],det=a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1])-a[0][1]*(a[1][0]*a[2][2]-a[1][2]*a[2][0])+a[0][2]*(a[1][0]*a[2][1]-a[1][1]*a[2][0]);if(Math.abs(det)<1e-12)return norm(n);const inv=[[(a[1][1]*a[2][2]-a[1][2]*a[2][1])/det,(a[0][2]*a[2][1]-a[0][1]*a[2][2])/det,(a[0][1]*a[1][2]-a[0][2]*a[1][1])/det],[(a[1][2]*a[2][0]-a[1][0]*a[2][2])/det,(a[0][0]*a[2][2]-a[0][2]*a[2][0])/det,(a[0][2]*a[1][0]-a[0][0]*a[1][2])/det],[(a[1][0]*a[2][1]-a[1][1]*a[2][0])/det,(a[0][1]*a[2][0]-a[0][0]*a[2][1])/det,(a[0][0]*a[1][1]-a[0][1]*a[1][0])/det]];return norm([inv[0][0]*n[0]+inv[1][0]*n[1]+inv[2][0]*n[2],inv[0][1]*n[0]+inv[1][1]*n[1]+inv[2][1]*n[2],inv[0][2]*n[0]+inv[1][2]*n[1]+inv[2][2]*n[2]]);}
function percentile(vals,p){const a=[...vals].sort((x,y)=>x-y),q=(a.length-1)*p/100,lo=Math.floor(q),hi=Math.ceil(q);if(lo===hi)return a[lo];return a[lo]*(hi-q)+a[hi]*(q-lo);}
function rayTri(o,d,a,b,c){const e1=sub(b,a),e2=sub(c,a),p=cross(d,e2),det=dot(e1,p);if(Math.abs(det)<1e-10)return null;const inv=1/det,tv=sub(o,a),u=dot(tv,p)*inv;if(u<0||u>1)return null;const q=cross(tv,e1),v=dot(d,q)*inv;if(v<0||u+v>1)return null;const t=dot(e2,q)*inv;if(t<0)return null;return{t,u,v,w:1-u-v,point:add(o,muls(d,t))};}
function quatFromZ(n){const from=[0,0,1],to=norm(n),r=1+dot(from,to);let q;if(r<1e-10)q=[0,-1,0,0];else{const c=cross(from,to);q=[c[0],c[1],c[2],r];}const l=Math.hypot(...q)||1;return q.map(v=>v/l);}
function quatFromBasis(xAxis,yAxis,zAxis){const m00=xAxis[0],m01=yAxis[0],m02=zAxis[0],m10=xAxis[1],m11=yAxis[1],m12=zAxis[1],m20=xAxis[2],m21=yAxis[2],m22=zAxis[2],tr=m00+m11+m22;let x,y,z,w;if(tr>0){const s=Math.sqrt(tr+1)*2;w=.25*s;x=(m21-m12)/s;y=(m02-m20)/s;z=(m10-m01)/s;}else if(m00>m11&&m00>m22){const s=Math.sqrt(1+m00-m11-m22)*2;w=(m21-m12)/s;x=.25*s;y=(m01+m10)/s;z=(m02+m20)/s;}else if(m11>m22){const s=Math.sqrt(1+m11-m00-m22)*2;w=(m02-m20)/s;x=(m01+m10)/s;y=.25*s;z=(m12+m21)/s;}else{const s=Math.sqrt(1+m22-m00-m11)*2;w=(m10-m01)/s;x=(m02+m20)/s;y=(m12+m21)/s;z=.25*s;}const l=Math.hypot(x,y,z,w)||1;return[x/l,y/l,z/l,w/l];}
function quatFromZHeadHorizontal(n){const zAxis=norm(n);let xAxis=norm([zAxis[2],0,-zAxis[0]]);if(len(xAxis)<1e-8)xAxis=[1,0,0];const yAxis=norm(cross(zAxis,xAxis));return quatFromBasis(xAxis,yAxis,zAxis);}
function findHeadNode(gltf){const exact=['Head','head','HEAD','mixamorigHead','mixamorig:Head','Bip001 Head'];for(const name of exact){const i=gltf.nodes.findIndex(n=>n.name===name);if(i>=0)return i;}const i=gltf.nodes.findIndex(n=>/head/i.test(n.name??''));if(i>=0)return i;throw new Error('Head bone not found. Add a supported head-bone alias before facializing this rig.');}
function buildWorldMatrices(gltf){const parent=new Map();gltf.nodes.forEach((n,i)=>(n.children??[]).forEach(c=>parent.set(c,i)));const cache=new Map();const world=i=>{if(cache.has(i))return cache.get(i);let w=nodeLocal(gltf.nodes[i]);if(parent.has(i))w=mmul(world(parent.get(i)),w);cache.set(i,w);return w;};return world;}
function collectGeometry(gltf,bin,headNode,headWorldInv,world){const points=[],triangles=[];let selectedVerts=0,totalVerts=0;gltf.nodes.forEach((node,nodeIndex)=>{if(node.mesh==null||node.skin==null)return;const skin=gltf.skins[node.skin],headJoint=skin.joints.indexOf(headNode);if(headJoint<0)return;const meshWorld=world(nodeIndex),toHead=mmul(headWorldInv,meshWorld);for(const prim of gltf.meshes[node.mesh].primitives){const at=prim.attributes;if(at.POSITION==null||at.JOINTS_0==null||at.WEIGHTS_0==null)return;const pos=readAccessor(gltf,bin,at.POSITION),joints=readAccessor(gltf,bin,at.JOINTS_0),weights=readAccessor(gltf,bin,at.WEIGHTS_0),normals=at.NORMAL!=null?readAccessor(gltf,bin,at.NORMAL):null;totalVerts+=pos.length;const hp=pos.map((p,i)=>{let w=0;for(let k=0;k<4;k++)if(Math.round(joints[i][k])===headJoint)w+=weights[i][k];const P=transformPoint(toHead,p),N=normals?transformNormalBetween(toHead,normals[i]):null;if(w>=defaults.headWeightThreshold){points.push(P);selectedVerts++;}return{P,N,w};});let idx;if(prim.indices!=null)idx=readAccessor(gltf,bin,prim.indices).map(r=>r[0]);else idx=Array.from({length:pos.length},(_,i)=>i);for(let i=0;i+2<idx.length;i+=3){const a=hp[idx[i]],b=hp[idx[i+1]],c=hp[idx[i+2]];if(a.w>=defaults.headWeightThreshold&&b.w>=defaults.headWeightThreshold&&c.w>=defaults.headWeightThreshold)triangles.push([a,b,c]);}}});if(points.length<30||triangles.length<10)throw new Error('Not enough Head-dominant geometry for automatic calibration.');return{points,triangles,selectedVerts,totalVerts};}
function robustBounds(points,range=defaults.boundsPercentile){const[lo,hi]=range,axes=[0,1,2],min=axes.map(k=>percentile(points.map(p=>p[k]),lo)),max=axes.map(k=>percentile(points.map(p=>p[k]),hi));return{min,max,extent:max.map((v,i)=>v-min[i]),center:max.map((v,i)=>(v+min[i])/2)};}
function faceCoreBounds(points,side){const q=defaults.frontCorePercentile??30,zs=points.map(p=>p[2]),cut=side==='-Z'?percentile(zs,q):percentile(zs,100-q),core=points.filter(p=>side==='-Z'?p[2]<=cut:p[2]>=cut),b=robustBounds(core,defaults.frontCoreBoundsPercentile??[5,95]);return{...b,count:core.length,cutZ:cut};}
function seedAnchors(bounds){const r=defaults.ratios,e=bounds.extent,mn=bounds.min,mk=q=>[mn[0]+q.x01*e[0],mn[1]+q.y01*e[1]];return{leftEye:{xy:mk(r.leftEye),size:[r.leftEye.w*e[0],r.leftEye.h*e[1]]},rightEye:{xy:mk(r.rightEye),size:[r.rightEye.w*e[0],r.rightEye.h*e[1]]},mouth:{xy:mk(r.mouth),size:[r.mouth.w*e[0],r.mouth.h*e[1]]}};}
function resolveSide(bounds,coreBounds,triangles,seeds,side){const depth=bounds.extent[2],margin=defaults.rayMarginDepthRatio*depth,inward=side==='-Z'?[0,0,1]:[0,0,-1],startZ=side==='-Z'?bounds.min[2]-margin:bounds.max[2]+margin,outward=muls(inward,-1),bias=(defaults.surfaceBiasCoreWidthRatio??0.0225)*coreBounds.extent[0],resolved={};let axial=0;for(const[name,s]of Object.entries(seeds)){const o=[s.xy[0],s.xy[1],startZ];let best=null,bestTri=null;for(const tri of triangles){const h=rayTri(o,inward,tri[0].P,tri[1].P,tri[2].P);if(h&&(!best||h.t<best.t)){best=h;bestTri=tri;}}if(!best)continue;let n;if(bestTri[0].N&&bestTri[1].N&&bestTri[2].N)n=norm(add(add(muls(bestTri[0].N,best.w),muls(bestTri[1].N,best.u)),muls(bestTri[2].N,best.v)));else n=norm(cross(sub(bestTri[1].P,bestTri[0].P),sub(bestTri[2].P,bestTri[0].P)));if(dot(n,inward)>0)n=muls(n,-1);axial+=Math.max(0,dot(n,outward));const p=add(best.point,muls(n,bias));resolved[name]={inputXY:s.xy,position:p,quaternion:name==='mouth'?quatFromZHeadHorizontal(n):quatFromZ(n),size:s.size,normal:n,rawSurfacePoint:best.point};}const vals=Object.values(resolved),hitRatio=vals.length/3,z=vals.map(v=>v.rawSurfacePoint[2]),zMean=z.length?z.reduce((a,b)=>a+b,0)/z.length:0,zStd=z.length?Math.sqrt(z.reduce((s,v)=>s+(v-zMean)**2,0)/z.length):depth,coherence=clamp(1-zStd/(depth*.15),0,1),normalScore=vals.length?axial/vals.length:0,hintBonus=side===defaults.frontHint?.toUpperCase()?.replace(' ','')?.replace('−','-')?.replace('Z','Z')?.replace('+Z','+Z')?0.08:0;return{side,resolved,score:hitRatio*.55+normalScore*.25+coherence*.20+hintBonus,metrics:{hitRatio,normalScore,coherence,zStd,bias}};}

const{json:gltf,bin}=parseGLB(modelPath),world=buildWorldMatrices(gltf),headNode=findHeadNode(gltf),headName=gltf.nodes[headNode].name??'Head',headInv=inv4(world(headNode)),geom=collectGeometry(gltf,bin,headNode,headInv,world),bounds=robustBounds(geom.points);let candidates=['-Z','+Z'].map(side=>{const core=faceCoreBounds(geom.points,side),seeds=seedAnchors(core);return{...resolveSide(bounds,core,geom.triangles,seeds,side),core};}).sort((a,b)=>b.score-a.score),chosen=candidates[0];const hinted=candidates.find(c=>c.side===defaults.frontHint);if(hinted&&hinted.metrics.hitRatio===1&&hinted.metrics.normalScore>.55)chosen=hinted;if(Object.keys(chosen.resolved).length<3)throw new Error('Automatic face surface resolution failed for one or more anchors.');const clean={};for(const[k,v]of Object.entries(chosen.resolved))clean[k]={inputXY:v.inputXY.map(x=>+x.toFixed(8)),position:v.position.map(x=>+x.toFixed(8)),quaternion:v.quaternion.map(x=>+x.toFixed(8)),size:v.size.map(x=>+x.toFixed(8))};const confidence=clamp(chosen.metrics.hitRatio*.5+chosen.metrics.normalScore*.3+chosen.metrics.coherence*.2,0,1),spread=[0,1].map(k=>bounds.extent[k]/Math.max(chosen.core.extent[k],1e-9)),profile={version:3,system:'three-facial-system',preset:defaults.preset,character:charName,model:path.basename(modelPath),bone:headName,trackingMode:'head-lock',autoGenerated:true,confidence:+confidence.toFixed(3),calibration:{frontSide:chosen.side,normalMode:'smooth-barycentric',surfaceBias:+chosen.metrics.bias.toFixed(8),headWeightThreshold:defaults.headWeightThreshold,boundsPercentile:defaults.boundsPercentile,frontCorePercentile:defaults.frontCorePercentile,frontCoreBoundsPercentile:defaults.frontCoreBoundsPercentile,headBounds:{min:bounds.min.map(x=>+x.toFixed(8)),max:bounds.max.map(x=>+x.toFixed(8)),extent:bounds.extent.map(x=>+x.toFixed(8))},faceCoreBounds:{min:chosen.core.min.map(x=>+x.toFixed(8)),max:chosen.core.max.map(x=>+x.toFixed(8)),extent:chosen.core.extent.map(x=>+x.toFixed(8)),sampleCount:chosen.core.count}},anchors:clean,diagnostics:{headDominantVertices:geom.selectedVerts,totalVertices:geom.totalVerts,accessorySpreadXY:spread.map(x=>+x.toFixed(3)),candidateScores:Object.fromEntries(candidates.map(c=>[c.side,+c.score.toFixed(3)])),requiresReview:confidence<0.72}};fs.mkdirSync(path.dirname(outPath),{recursive:true});fs.writeFileSync(outPath,JSON.stringify(profile,null,2)+'\n');console.log(`Facial profile generated: ${outPath}`);console.log(`Head: ${headName} | front: ${chosen.side} | confidence: ${profile.confidence}`);console.log(`Anchors: L ${clean.leftEye.inputXY.join(', ')} | R ${clean.rightEye.inputXY.join(', ')} | M ${clean.mouth.inputXY.join(', ')}`);if(profile.diagnostics.requiresReview)console.log('WARNING: confidence is low; Codex should inspect the generated calibration preview before integration.');
